name: Selenium UI Tests

on: [push, pull_request]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    env:
      BASE_URL: https://www.saucedemo.com
      UI_USERNAME: ${{ secrets.UI_USERNAME }}
      UI_PASSWORD: ${{ secrets.UI_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Selenium Tests
        run: pytest

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: selenium-ui-report
          path: reports/report.html
